diagnosticMode:
  enabled: false

livenessProbe:
  enabled: false
  path: /
readinessProbe:
  enabled: false
  path: /
startupProbe:
  enabled: false

image:
  repository: node
  tag: 19.7.0-slim
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

containerPorts:
  http: 8080

podAnnotations:

autoscaling:
  enabled: false

replicaCount:
  _default: 1
  dev: 1
  test: 1

volumes:
  enabled: false

affinity: {}

podSecurityContext: {}
containerSecurityContext: {}

res:
  map:
    enabled: false
  abs:
    enabled: true

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

service:
  type: ClusterIP
  ports:
    http: 8080
  nodePorts:
    http: {}

ingress:
  nginx:
    enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-response-header: 'Content-Type: application/octet-stream'
    nginx.ingress.kubernetes.io/backend-protocol: http
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  hosts:
    - host:
        _default: test.grigorylantsov.local
      paths:
        - path: "/"
          pathType: Prefix

serviceAccount:
  create: false

persistence:
  enabled: false

application:
  env:
    PUBLIC_URL:
      _default: "https://test.grigorylantsov.local"
    PROJECT_TITLE:
      _default: "Pulumi.test.k8s.dynamic.env"
