name: Go Build and Deployment

env: 
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_artifact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
          go-version: '1.20'

    - name: Build Go application
      run: |
        go mod tidy -compat=1.20
        CGO_ENABLED=0 go build -o main ./src

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: go-artifact
          path: main

  build_push_image:
    needs: build_artifact
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - uses: actions/download-artifact@master
      with:
          name: go-artifact
          path: ./main

    - name: docker login
      run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

    - name: docker build
      run: docker build . -t ${DOCKER_USERNAME}/k8s-dynamic-env:1.0.0

    - name: docker push
      run: |
        docker push ${DOCKER_USERNAME}/k8s-dynamic-env:1.0.0
        docker tag ${DOCKER_USERNAME}/k8s-dynamic-env:1.0.0 ${DOCKER_USERNAME}/k8s-dynamic-env:latest
        docker push ${DOCKER_USERNAME}/k8s-dynamic-env:latest
